### ISSUE TITLE
Action stopped working -> cannot read properties of undefined. 

### ISSUE THREAD

**Issue by DomantasGiedraitis** [mondeja/remove-labels-gh-action#31]
Hi, 

I was using this action for >3 months now, and it suddenly stopped working on 2nd March with the following error stack trace: 
![image](https://user-images.githubusercontent.com/90192221/157196223-eb02cdbe-5e84-4751-8c0c-8b60a1909d70.png)

There were no labels changed, the actions haven't been touched either. 

Any ideas/suggestions?

For now, I have disabled the workflow manually.

**Comment by mondeja** [comment]
You can for now pin to v1.0.0, I'll release a patch ASAP.

**Comment by mondeja** [comment]
It's fixed now in v1. Could you confirm it?

**Comment by DomantasGiedraitis** [comment]
I did the below, but keep getting the same erorr. The stack trace tells me it's still using v1

```yaml
...
    runs-on: ubuntu-latest
    steps:
      - uses: mondeja/remove-labels-gh-action@v1.0.0
...
```
![image](https://user-images.githubusercontent.com/90192221/157204575-6d972005-35c5-4483-9365-c1638e8b1100.png)

**Comment by mondeja** [comment]
Sorry for the inconvenience. Should be fixed now with:

```yaml
...
    runs-on: ubuntu-latest
    steps:
      - uses: mondeja/remove-labels-gh-action@v1
...
```
